version: 2

defaults: &defaults
  docker:
    - image: circleci/node:dubnium
  working_directory: ~/space-kit

jobs:
  eslint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Ensure output directory exists
          command: mkdir -p /tmp/test-reports/eslint
      - run:
          name: Eslint
          command: npm run lint -- --no-cache --format junit --output-file /tmp/test-reports/eslint/results.xml
      - store_test_results:
          path: /tmp/test-reports

  typescript:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: TypeScript
          command: npm run test:typescript

workflows:
  version: 2
  test:
    jobs:
      - eslint
      - typescript
