version: 2

defaults: &defaults
  docker:
    - image: circleci/node:dubnium
  working_directory: ~/space-kit

jobs:
  eslint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Ensure output directory exists
          command: mkdir -p /tmp/test-reports/eslint
      - run:
          name: Eslint
          command: npm run lint -- --no-cache --format junit --output-file /tmp/test-reports/eslint/results.xml
      - store_test_results:
          path: /tmp/test-reports

  check-label:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Check labels
          command: npx auto pr-check --pr ${CIRCLE_PULL_REQUEST##*/} --url ${CIRCLE_BUILD_URL}

  release:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            # see https://circleci.com/gh/apollographql/space-kit/edit#checkout
            - "81:5a:2f:22:7e:92:6a:dc:95:08:87:a3:2e:3a:61:bf"
      - run:
          name: Add NPM_TOKEN to `.npmrc`
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/space-kit/.npmrc
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Release
          command: npm run release

  typescript:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: TypeScript
          command: npm run test:typescript

workflows:
  version: 2
  test:
    jobs:
      - eslint
      - typescript
      - check-label:
          filters:
            branches:
              ignore:
                - master
      - release:
          requires:
            - eslint
            - typescript
          filters:
            branches:
              only:
                - master

