version: 2

defaults: &defaults
  docker:
    - image: circleci/node:dubnium
  working_directory: ~/space-kit

jobs:
  chromatic:
    <<: *defaults
    resource_class: medium+
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci
      - restore_cache:
          name: Restore storybook cache
          keys:
            - storybook-cache--{{ .Branch }}--{{ checksum ".circleci/config.yml" }}
            - storybook-cache--main--{{ checksum ".circleci/config.yml" }}
      - run:
          name: Run Chromatic
          command: npm run chromatic -- --exit-zero-on-changes --auto-accept-changes=main
          environment:
            CI: 1
      - save_cache:
          name: Save chromatic cache
          key: storybook-cache--{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ epoch }}
          paths:
            - node_modules/.cache/storybook
  eslint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Ensure output directory exists
          command: mkdir -p /tmp/test-reports/eslint
      - run:
          name: Eslint
          command: npm run lint -- --no-cache --format junit --output-file /tmp/test-reports/eslint/results.xml
      - store_test_results:
          path: /tmp/test-reports

  check-label:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Check labels
          command: npx auto pr-check --pr ${CIRCLE_PULL_REQUEST##*/} --url ${CIRCLE_BUILD_URL}

  release:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            # see https://circleci.com/gh/apollographql/space-kit/edit#checkout
            - "24:43:ac:47:ed:1f:e3:8c:2f:1f:cd:99:64:39:7d:77"
      # - run:
      #     name: Add NPM_TOKEN to `.npmrc`
      #     command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/space-kit/.npmrc
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Release
          command: npm run release

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Test
          command: npm run test:unit:coverage -- --silent --maxWorkers=2 --ci
      - store_artifacts:
          name: Store coverage artifacts
          path: coverage

  typescript:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: TypeScript
          command: npm run test:typescript

workflows:
  version: 2
  test:
    jobs:
      - chromatic
      - eslint
      - typescript
      - test
      - check-label:
          filters:
            branches:
              ignore:
                - main
      - release:
          requires:
            - eslint
            - typescript
            - test
          filters:
            branches:
              only:
                - main
